### ISSUE TITLE
i 'm noob

### ISSUE THREAD

**Issue by ccdescipline** [Sato-Isolated/apex-offset#1]
how to use in CE?

**Comment by Sato-Isolated** [comment]
Hello u can't use that in Cheat Engine 

because ur gonna be instant ban

u need to do an app with ur own driver(if u use a public driver ur gonna be ban after 1 game) like that : https://github.com/KaylinOwO/Project-Branthium or https://github.com/BaconToaster/UC-Apex-Remastered

**Comment by ccdescipline** [comment]
i know ，i have a super  ce，I want to know how to use these offsets, can you give me an example
