### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ccdescipline** [Sato-Isolated/apex-offset#2]
i have a super ce，I want to know how to use these offsets, can you give me an example?
thx

**Comment by Sato-Isolated** [comment]
`

void Modules::NoRecoil()
{
	// check if localplayer is valid and rcs is on
	if (!globals.rcs || !Player::IsPlayer(globals.localPlayer)) return;

	if (!(GetAsyncKeyState(VK_RBUTTON) && globals.aimbot && globals.currentAimTarget != NULL))
	{
		// get current angles and recoil (punch angle)
		vec3 viewAngles = Driver.rpm<vec3>(globals.localPlayer + OFFSET_VIEWANGLES);
		vec3 punchAngle = Driver.rpm<vec3>(globals.localPlayer + OFFSET_AIMPUNCH);

		// calculate the new angles by adding the punchangle to the viewangles, it is important to subtract the old punch angle
		vec3 newAngle = viewAngles + (oldPunch - punchAngle) * (globals.rcsIntensity / 100.f);

		newAngle.Normalize(); // clamp angles
		Driver.wpm<vec2>(globals.localPlayer + OFFSET_VIEWANGLES, { newAngle.x, newAngle.y }); // overwrite old angles

		oldPunch = punchAngle;
	}
}

`

something like that
